author: "Rim Alhajal, Pauline Dusfour--Castan, Lilou Zulewski et Abdoulaye Diop"
toc: true
lang: fr
reference-location: margin
citation-location: margin
fig-cap-location: margin
format:
  html:
    mainfont: Atkinson Hyperlegible
    html-math-method: katex
    toc-location: left
    toc-depth: 6
    code-fold: false
    code-tools:
      toggle: false
      source: false
    self-contained: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem
    code-overflow: wrap
    fig-responsive: true
    fig-format: svg
execute:
  warning: false
  error: true