---
title: "Visualisation_data"
author: "Worshp"
date: "2023-12-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages utiles pour la visulisation
```{r Package, include=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
library(plotly)
library(OmicCircos)

```


```{r}
data(TCGA.PAM50_genefu_hg18)
df<-TCGA.PAM50_genefu_hg18
# Pour voir mieux, j'ai affiché que les 10 premières lignes du dataset. Si vous voulez voir plus, vous pouvez mettre en commentaire la ligne suivante.
df<-df[1:10,]
df_long <- df %>%
  gather(key = "Subtype", value = "Expression", -chr, -po, -Gene)

ggplot(df_long, aes(x = Gene, y = Expression, fill = Subtype)) +
  geom_bar(stat = "identity") +
  labs(title = "Expression génique des gènes dans les sous-catégories de cancer du sein",
       x = "Gène", y = "Expression génique") +
  theme_minimal()

```

# Faisons un heatmap pour mieux voir les données dans l'ensemble

```{r}
df<-TCGA.PAM50_genefu_hg18
df_long <- df %>%
  gather(key = "Subtype", value = "Expression", -chr, -po, -Gene)

# Créer le graphique ggplot
heatmap_plot <- ggplot(df_long, aes(x = Gene, y = Subtype, fill = Expression)) +
  geom_tile() +
  labs(title = "Heatmap de l'expression génique dans les sous-catégories de cancer du sein",
       x = "Gène", y = "Sous-type de cancer du sein") +
  theme_minimal()

# Convertir le graphique ggplot en heatmap interactif avec plotly
heatmap_interactif <- ggplotly(heatmap_plot, tooltip = "all")

# Afficher le heatmap interactif
heatmap_interactif

```


